// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
e d d d d d d d d d d d d d d e 
e d 1 1 1 1 1 1 1 1 1 1 1 1 d e 
e d e d d d d d d d d d d e d e 
e d e d 1 1 1 1 1 1 1 1 d e d e 
e d e d e d d d d d d e d e d e 
e d e d e d 1 1 1 1 d e d e d e 
e d e d e d e e e e d e d e d e 
e e e e e e e e e e e e e e e e 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . b . . . . . . . . 
. . . . . . b c b . . . . . . . 
. . . . . . b c f b . . . . . . 
. . . . . b c c f b b . . . . . 
. . . . . b c f f f b . . . . . 
. . . . b c c f f f f b . . . . 
. . . . b c f f f f f b . . . . 
. . . b c c f f f f f f b . . . 
. . . b c f f f f f f f b . . . 
. . b c c f f f f f f f f b . . 
. . b c f f f f f f f f f b . . 
. b c c f f f f f f f f f f b . 
b c c f f f f f f f f f f f b . 
b c f f f f f f f f f f f f f b 
`;
            case "image4":
            case "myImage2":return img`
..4....4....4.......4....4..4......
4444...444...4..44..4.4444..4...4..
.4.44...4.4..4...4.44..44.44...4...
..44444.4444aacccfffff..4444..4....
...44..44.cccffffffffff44.4.44...4.
4....4444acffffffffffffff4f44..4444
44...44acffffcfffffffcffff44444..4.
.44444acfffffccffffcccffffff444..44
..4.4ccfffff55ccfffcc55ffffff44444.
..444cffffff55fcfffcf55fffffff44.4.
..44acffffffffffffffffffffffff4444.
44.4cffffffffffffffffffffffffff4444
44.4cffffffffffffffffffffffffff444.
.44afffffffffffffffffffffffffff444.
..4fffffffffffffffffffffffffffff44.
.44fffffffffffffffffffffffffffff44.
.444ffffffffffffffffffffffffffff44.
.4.fffffffffffffffffffffffffffff4.4
.44fffffffffffffffffffffffffffff44.
444fffffffffffffffffffffffffffff44.
444fffffffffffffffffffffffffffff444
.44fffffffffffffffffffffffffffff444
444fffffffffffffffffffffffffffff4.4
.444fffffffffffffffffffffffffff44.4
4.44ffffffffffffffffffffffffff444..
.4444fffffffffffffffffffffffff444..
..444ffffffffffffffffffffffff444...
..44444ffffffffffffffffffffff444...
.....44ffffffffffffffffffff44..4...
444444444ffffffffffffffff4444..44..
.......4444fffffffffffff44...444.4.
....44444444fffffffffff4.44.4.444.4
...4.44..4.4444..4444..4.44..44..4.
.44.4...4.....4444.....4.444..44..4
...4...4....4444......4.44.4..444..
`;
            case "image5":
            case "myImage3":return img`
...4...4......4...4...44....4..4...
....4.444444444444444.444..44444444
...4444.4444.aacccff4ff444.4444444.
.44....4444cccfffffffffff44.4..444.
...44..44.4cffffffffffffff4f4..444.
.....444acffffcfffffffcffff44444.4.
....444acfffffccffffcccffff4444444.
..444.ccfffff55ccfffcc55ffff444.44.
.44.4.cffffff55fcfffcf55ffff4444.4.
.4.44acffffffffffffffffffffff44.4..
.444.cffffffffffffffffffffffff4.44.
...44cfffffffffffffffffffffffff4.44
.444affffffffffffffffffffffffff4444
..4.ffffffffffffffffffffffffffff44.
..4fffffffffffffffffffffffffffff444
..4f4ffffffffffffffffffffffffffff44
..444fffffffffffffffffffffffffff444
..44fffffffffffffffffffffffffffff44
.444fffffffffffffffffffffffffffff4.
...4fffffffffffffffffffffffffffff44
.444fffffffffffffffffffffffffffff4.
...44fffffffffffffffffffffffffff44.
....4ffffffffffffffffffffffffff444.
....44fffffffffffffffffffffffff44..
..4444fffffffffffffffffffffffff44..
..4.44ffffffffffffffffffffffff44444
..44.4..ffffffffffffffffffffff4.44.
.44..444fffffffffffffffffffff4.444.
.4..44.444ffffffffffffffffff4.4.44.
....4..4.444ffffffffffffff444..444.
....4..4.44444fff4fffff44444.4.444.
....4..4.4....444.4444444..444.4444
....444444..444444444.4.4...44.44..
.44444......4..4..444.4444444.444..
...................................
`;
            case "image3":
            case "myImage1":return img`
...................................
...................................
...................................
............aacccfffff.............
..........cccffffffffffff..........
........aacffffffffffffffff........
.......acffff1fffffff1fffff........
......acfffffc1ffffc1cfffffff......
.....ccfffff11c1fff1c11fffffff.....
.....cffffff11fcfffcf11fffffff.....
....acfffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...acfffffffffffffffffffffffffff...
...affffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....fffffffffffffffffffffffffff....
.....fffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
......fffffffffffffffffffffff......
.......fffffffffffffffffffff.......
........fffffffffffffffffff........
..........fffffffffffffff..........
............fffffffffff............
...................................
...................................
...................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
...................................
...................................
............aacccfffff.............
..........cccffffffffffff..........
........aacffffffffffffffff........
.......acffffcfffffffcfffff........
......acfffffccffffcccfffffff......
.....ccfffff55ccfffcc55fffffff.....
.....cffffff55fcfffcf55fffffff.....
....acfffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...acfffffffffffffffffffffffffff...
...affffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....fffffffffffffffffffffffffff....
.....fffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
......fffffffffffffffffffffff......
.......fffffffffffffffffffff.......
........fffffffffffffffffff........
..........fffffffffffffff..........
............fffffffffff............
...................................
...................................
...................................
...................................
`, img`
...................................
...................................
...................................
............aacccfffff.............
..........cccffffffffff............
.........acffffffffffffff.f........
.......acffffcfffffffcffff.........
......acfffffccffffcccffffff.......
.....ccfffff55ccfffcc55ffffff......
.....cffffff55fcfffcf55fffffff.....
....acffffffffffffffffffffffff.....
....cffffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...afffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....ffffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
.....ffffffffffffffffffffffff......
.......ffffffffffffffffffffff......
.......ffffffffffffffffffff........
.........ffffffffffffffff..........
...........fffffffffffff...........
............fffffffffff............
...................................
...................................
...................................
`, img`
...................................
...................................
.............aaccc.f.ff............
...........cccffffffffffff.........
...........cffffffffffffffff.......
........acffffcfffffffcfffff.......
.......acfffffccffffcccffffff......
......ccfffff55ccfffcc55fffff......
......cffffff55fcfffcf55ffffff.....
.....acfffffffffffffffffffffff.....
.....cfffffffffffffffffffffffff....
.....cfffffffffffffffffffffffff....
....afffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...f.ffffffffffffffffffffffffffff..
.....fffffffffffffffffffffffffff...
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
.....fffffffffffffffffffffffffff...
.....ffffffffffffffffffffffffff....
......fffffffffffffffffffffffff....
......fffffffffffffffffffffffff....
......ffffffffffffffffffffffff.....
........ffffffffffffffffffffff.....
........fffffffffffffffffffff......
..........ffffffffffffffffff.......
............ffffffffffffff.........
..............fff.fffff............
...................................
...................................
...................................
...................................
`, img`
...................................
...................................
...................................
............aacccfffff.............
..........cccffffffffff............
.........acffffffffffffff.f........
.......acffffcfffffffcffff.........
......acfffffccffffcccffffff.......
.....ccfffff55ccfffcc55ffffff......
.....cffffff55fcfffcf55fffffff.....
....acffffffffffffffffffffffff.....
....cffffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...afffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....ffffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
.....ffffffffffffffffffffffff......
.......ffffffffffffffffffffff......
.......ffffffffffffffffffff........
.........ffffffffffffffff..........
...........fffffffffffff...........
............fffffffffff............
...................................
...................................
...................................
`];
            case "myAnim0":
            case "anim2":return [img`
...................................
...................................
............aacccfffff.............
..........cccffffffffffff..........
........aacffffffffffffffff........
.......acffffcfffffffcfffff........
......acfffffccffffcccfffffff......
.....ccfffff11ccfffcc11fffffff.....
.....cffffff11fcfffcf11fffffff.....
....acfffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...acfffffffffffffffffffffffffff...
...affffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....fffffffffffffffffffffffffff....
.....fffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
......fffffffffffffffffffffff......
.......fffffffffffffffffffff.......
........fffffffffffffffffff........
..........fffffffffffffff..........
............fffffffffff............
...................................
...................................
...................................
...................................
`, img`
...................................
...................................
...................................
............aacccfffff.............
..........cccffffffffff............
.........acffffffffffffff.f........
.......acffffcfffffffcffff.........
......acfffffccffffcccffffff.......
.....ccfffff11ccfffcc11ffffff......
.....cffffff11fcfffcf11fffffff.....
....acffffffffffffffffffffffff.....
....cffffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...afffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....ffffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
.....ffffffffffffffffffffffff......
.......ffffffffffffffffffffff......
.......ffffffffffffffffffff........
.........ffffffffffffffff..........
...........fffffffffffff...........
............fffffffffff............
...................................
...................................
...................................
`, img`
...................................
...................................
.............aaccc.f.ff............
...........cccffffffffffff.........
...........cffffffffffffffff.......
........acffffcfffffffcfffff.......
.......acfffffccffffcccffffff......
......ccfffff11ccfffcc11fffff......
......cffffff11fcfffcf11ffffff.....
.....acfffffffffffffffffffffff.....
.....cfffffffffffffffffffffffff....
.....cfffffffffffffffffffffffff....
....afffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...f.ffffffffffffffffffffffffffff..
.....fffffffffffffffffffffffffff...
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
....fffffffffffffffffffffffffffff..
.....fffffffffffffffffffffffffff...
.....ffffffffffffffffffffffffff....
......fffffffffffffffffffffffff....
......fffffffffffffffffffffffff....
......ffffffffffffffffffffffff.....
........ffffffffffffffffffffff.....
........fffffffffffffffffffff......
..........ffffffffffffffffff.......
............ffffffffffffff.........
..............fff.fffff............
...................................
...................................
...................................
...................................
`, img`
...................................
...................................
...................................
............aacccfffff.............
..........cccffffffffff............
.........acffffffffffffff.f........
.......acffffcfffffffcffff.........
......acfffffccffffcccffffff.......
.....ccfffff11ccfffcc11ffffff......
.....cffffff11fcfffcf11fffffff.....
....acffffffffffffffffffffffff.....
....cffffffffffffffffffffffffff....
....cffffffffffffffffffffffffff....
...afffffffffffffffffffffffffff....
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....ffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
...fffffffffffffffffffffffffffff...
....fffffffffffffffffffffffffff....
....ffffffffffffffffffffffffff.....
.....fffffffffffffffffffffffff.....
.....ffffffffffffffffffffffff......
.......ffffffffffffffffffffff......
.......ffffffffffffffffffff........
.........ffffffffffffffff..........
...........fffffffffffff...........
............fffffffffff............
...................................
...................................
...................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
